# Generated by Django 3.2 on 2021-04-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210422_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default='Sample'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(default='Sample'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isbn', to='books.isbn'),
        ),
        migrations.AlterField(
            model_name='isbn',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
